spring:
  application:
    name: quotex
  datasource:
    url: jdbc:mysql://localhost:3306/quotex_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  docker:
    compose:
      enabled: false

api:
  security:
    jwt:
      secret: secret
